# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  # Check for updates to pip dependencies
  - package-ecosystem: "pip"
    directory: "/" # location of your requirements.txt
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "example-package" # add packages to ignore if necessary

  # Check for updates to Conda environment dependencies
  - package-ecosystem: "conda"
    directory: "/" # location of your environment.yml
    schedule:
      interval: "weekly"

  # Check for updates to pip dev dependencies
  - package-ecosystem: "pip"
    directory: "/" # location of your requirements_dev.txt
    schedule:
      interval: "weekly"
