version: 2.1

executors:
  python-executor:
    docker:
      - image: continuumio/miniconda3:latest
    environment:
      PATH: /opt/conda/bin:$PATH

jobs:
  lint:
    executor: python-executor
    steps:
      - checkout
      - run:
          name: Install Python Dependencies for Linting
          command: |
            conda install python=3.12 -y
            pip install --upgrade pip
            pip install black black[jupyter] ruff
      - run:
          name: Black Style Check
          command: |
            black --check .
      - run:
          name: Lint with Ruff
          command: |
            ruff check .

  build_0:
    executor: python-executor
    parameters:
      python-version:
        type: string
      numpy-version:
        type: string
    steps:
      - checkout
      - run:
          name: Install micromamba
          command: |
            curl micro.mamba.pm/install.sh | bash
            source ~/micromamba/etc/profile.d/micromamba.sh
            micromamba shell init -s bash -p ~/micromamba
            source ~/.bashrc
      - run:
          name: Create Conda Environment and Install Dependencies
          command: |
            micromamba create --yes --name radarx-unit-tests python=<<parameters.python-version>> numpy=<<parameters.numpy-version>>
            source ~/micromamba/etc/profile.d/micromamba.sh
            micromamba activate radarx-unit-tests
            python -m pip install . --no-deps
      - run:
          name: Test with pytest and collect coverage
          command: |
            pytest -n auto --dist loadfile --verbose --durations=15 --cov=radarx --cov-report=xml --cov-report=term-missing tests/ > coverage_unit.xml
      - run:
          name: Upload coverage to Codecov
          command: |
            bash <(curl -s https://codecov.io/bash) -f coverage_unit.xml -F unittests -t $CODECOV_TOKEN

  build_1:
    executor: python-executor
    steps:
      - checkout
      - run:
          name: Install micromamba
          command: |
            curl micro.mamba.pm/install.sh | bash
            source ~/micromamba/etc/profile.d/micromamba.sh
            micromamba shell init -s bash -p ~/micromamba
            source ~/.bashrc
      - run:
          name: Create Conda Environment and Install Dependencies
          command: |
            micromamba create --yes --name radarx-notebook-tests python=3.12 numpy=2
            source ~/micromamba/etc/profile.d/micromamba.sh
            micromamba activate radarx-notebook-tests
            python -m pip install . --no-deps
      - run:
          name: Test with pytest and collect coverage
          command: |
            pytest --nbval --verbose --durations=15 --cov=radarx --cov-report=xml --cov-report=term-missing examples/notebooks > coverage_notebook.xml
      - run:
          name: Upload coverage to Codecov
          command: |
            bash <(curl -s https://codecov.io/bash) -f coverage_notebook.xml -F notebooktests -t $CODECOV_TOKEN

workflows:
  version: 2
  lint_test:
    jobs:
      - lint
      - build_0:
          matrix:
            parameters:
              python-version: ["3.10", "3.12"]
              numpy-version: ["1", "2"]
      - build_1
