version: 2.1

jobs:
  lint:
    docker:
      - image: python:3.12
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            python -m pip install --upgrade pip
            pip install black black[jupyter] ruff
      - run:
          name: Black style check
          command: |
            black --check .
      - run:
          name: Lint with ruff
          command: |
            ruff check .

  test:
    docker:
      - image: python:3.12
    steps:
      - checkout
      - run:
          name: Install micromamba
          command: |
            curl -L https://micro.mamba.pm/install.sh | bash
            source ~/micromamba/etc/profile.d/micromamba.sh
            echo 'source ~/micromamba/etc/profile.d/micromamba.sh' >> ~/.bashrc
      - run:
          name: Create conda environment
          command: |
            source ~/micromamba/etc/profile.d/micromamba.sh
            micromamba create --yes --name radarx-env python=3.12 numpy
      - run:
          name: Activate environment and install dependencies
          command: |
            source ~/micromamba/etc/profile.d/micromamba.sh
            micromamba activate radarx-env
            python -m pip install . --no-deps
            python -m pip install pytest pytest-cov
      - run:
          name: Run tests with coverage
          command: |
            source ~/micromamba/etc/profile.d/micromamba.sh
            micromamba activate radarx-env
            pytest --cov=radarx --cov-report=xml:coverage.xml tests/
      - store_artifacts:
          path: coverage.xml
          destination: coverage.xml

workflows:
  version: 2
  lint_test:
    jobs:
      - lint
      - test
