name: radarx-examples
channels:
  - conda-forge
dependencies:
  - python>=3.10
  - boto3
  - cftime
  - matplotlib
  - netcdf4
  - numba
  - numpy
  - pandas
  - pooch
  - setuptools
  - xarray
  - xradar
  - arm_pyart
  - wradlib
  - fsspec
  - cmweather
  - itables
  - open_radar_data
  - pip
  - pip:
    - git+https://github.com/MeteoSwiss/fast-barnes-py.git
