name: radarx-examples
channels:
  - conda-forge
dependencies:
  # fast-barnes-py (installed below) supports Python < 3.13 only
  - python>=3.11,<3.13
  - matplotlib
  - numpy
  - pandas
  - pooch
  - setuptools
  - radarx
  - xarray
  - xradar
  - arm_pyart
  - wradlib
  - fsspec
  - cmweather
  - itables
  - jupytext
  - hvplot
  - holoviews
  - bokeh
  - panel
  - datashader
  - uxarray
  - spatialpandas
  - geopandas
  - open-radar-data
  - pip
  - pip:
    - git+https://github.com/MeteoSwiss/fast-barnes-py.git
