#!/usr/bin/env python
# Copyright (c) 2024-2026, Radarx developers.
# Distributed under the MIT License. See LICENSE for more info.

"""
Cold Pools and Baroclinic Vorticity
===================================

Thermodynamic diagnostics of convective cold pools from surface stations,
soundings and gridded fields, and the horizontal vorticity that buoyancy
gradients generate.

Potential temperatures
----------------------
:func:`potential_temperatures` gives the water-vapour mixing ratio
:math:`r = \\varepsilon e / (p - e)`, the potential temperature
:math:`\\theta = T (p_0 / p)^{R_d / c_{pd}}`, the virtual potential temperature
:math:`\\theta_v = \\theta (1 + r / \\varepsilon) / (1 + r)` and the
equivalent potential temperature of Bolton (1980, eq. 43) with the temperature
at the lifting condensation level of Bolton's eq. (15). The vapour pressure
:math:`e` is the saturation vapour pressure over water at the dew point
(Bolton 1980, eq. 10), :math:`p_0` = 1000 hPa, :math:`R_d` = 287.047 and
:math:`c_{pd}` = 1005.7 J kg\\ :sup:`-1` K\\ :sup:`-1`, :math:`\\varepsilon =
R_d / R_v` (as in :mod:`radarx.io.sounding`).

Buoyancy and cold-pool intensity
--------------------------------
Relative to a reference state :math:`\\overline{\\theta_v}` (the pre-storm
environment: an earlier time window at a station, or a sounding ahead of the
storm), the buoyancy is (e.g. Markowski and Richardson 2010, eq. 2.80)

.. math::

    B = g \\frac{\\theta_v - \\overline{\\theta_v}}{\\overline{\\theta_v}}
        - g\\, r_c ,

where :math:`r_c` is the condensate (hydrometeor) mixing ratio, if known.
Rotunno et al. (1988) measure the strength of a cold pool by

.. math::

    C^2 = 2 \\int_0^H (-B)\\, dz ,

the speed of the density current whose depth is :math:`H`; RKW theory
predicts the most upright and long-lived squall lines when :math:`C` balances
the line-normal low-level shear, :math:`C / \\Delta u \\approx 1` (Rotunno et
al. 1988; Weisman and Rotunno 2004). Bryan et al. (2006) compare this
"RKW ratio" across numerical models and discuss how sensitive :math:`C` is to
the choice of :math:`H` and of the shear layer. :func:`cold_pool_intensity`
integrates :math:`-B` (trapezoidal rule between valid levels) from the lowest
valid level up to the first height at which :math:`B` rises to ``threshold``
(linearly interpolated, default 0), or over a fixed ``depth``.

With hydrostatic balance the surface pressure excess under the cold pool is
:math:`\\Delta p_h = \\int_0^H \\rho (-B)\\, dz`, so that
:math:`C = \\sqrt{2 \\Delta p_h / \\rho}` (the speed of a density current of
Benjamin 1968; Wakimoto 1982 relates gust-front speeds to surface pressure
jumps in the same way); :func:`cold_pool_intensity_from_pressure` uses it
for the pressure rise at a surface station.
:func:`cold_pool_intensity_from_surface` assumes instead a depth :math:`H` and
a deficit that decreases linearly from the surface value to zero at
:math:`H` (:math:`C^2 = -B_s H`) or is uniform (:math:`C^2 = -2 B_s H`).

Baroclinic generation of horizontal vorticity
---------------------------------------------
In the Boussinesq approximation the horizontal vorticity
:math:`\\boldsymbol{\\omega}_h = (\\xi, \\eta)` is generated by horizontal
gradients of buoyancy,

.. math::

    \\frac{d \\xi}{d t} = \\frac{\\partial B}{\\partial y},\\qquad
    \\frac{d \\eta}{d t} = -\\frac{\\partial B}{\\partial x},

which in a vertical cross-section normal to a squall line is the
:math:`\\partial \\eta / \\partial t = -\\partial B / \\partial x` of Rotunno et
al. (1988). :func:`baroclinic_generation` evaluates these on a grid (centred
differences, one-sided next to missing values and at the edges) and, given
the winds (e.g. multi-Doppler winds) and a storm motion, splits the
generation into its streamwise and crosswise parts relative to the
storm-relative wind (Davies-Jones 1984).

The integrals, the gradients and the potential temperatures run in a compiled
kernel (``radarx.retrieve._coldpool``, multithreaded over all columns, rows
or samples of the input) with an identical NumPy reference implementation as
fallback.

References
----------
Benjamin, T. B., 1968: Gravity currents and related phenomena. *J. Fluid
Mech.*, **31** (2), 209-248, https://doi.org/10.1017/S0022112068000133

Bolton, D., 1980: The computation of equivalent potential temperature. *Mon.
Wea. Rev.*, **108** (7), 1046-1053,
https://doi.org/10.1175/1520-0493(1980)108<1046:TCOEPT>2.0.CO;2

Bryan, G. H., J. C. Knievel, and M. D. Parker, 2006: A multimodel assessment
of RKW theory's relevance to squall-line characteristics. *Mon. Wea. Rev.*,
**134** (10), 2772-2792, https://doi.org/10.1175/MWR3226.1

Davies-Jones, R., 1984: Streamwise vorticity: The origin of updraft rotation
in supercell storms. *J. Atmos. Sci.*, **41** (20), 2991-3006,
https://doi.org/10.1175/1520-0469(1984)041<2991:SVTOOU>2.0.CO;2

Markowski, P., and Y. Richardson, 2010: *Mesoscale Meteorology in
Midlatitudes*. Wiley-Blackwell, 407 pp.,
https://doi.org/10.1002/9780470682104

Rotunno, R., J. B. Klemp, and M. L. Weisman, 1988: A theory for strong,
long-lived squall lines. *J. Atmos. Sci.*, **45** (3), 463-485,
https://doi.org/10.1175/1520-0469(1988)045<0463:ATFSLL>2.0.CO;2

Wakimoto, R. M., 1982: The life cycle of thunderstorm gust fronts as viewed
with Doppler radar and rawinsonde data. *Mon. Wea. Rev.*, **110** (8),
1060-1082, https://doi.org/10.1175/1520-0493(1982)110<1060:TLCOTG>2.0.CO;2

Weisman, M. L., and R. Rotunno, 2004: "A theory for strong long-lived squall
lines" revisited. *J. Atmos. Sci.*, **61** (4), 361-382,
https://doi.org/10.1175/1520-0469(2004)061<0361:ATFSLS>2.0.CO;2

.. autosummary::
   :nosignatures:
   :toctree: generated/

   potential_temperatures
   buoyancy
   cold_pool_perturbation
   cold_pool_intensity
   cold_pool_intensity_from_pressure
   cold_pool_intensity_from_surface
   rkw_ratio
   baroclinic_generation
"""

from __future__ import annotations

__all__ = [
    "potential_temperatures",
    "buoyancy",
    "cold_pool_perturbation",
    "cold_pool_intensity",
    "cold_pool_intensity_from_pressure",
    "cold_pool_intensity_from_surface",
    "rkw_ratio",
    "baroclinic_generation",
]

import numpy as np
import xarray as xr

from .._registry import accessor_method
from . import _coldpool_numpy

try:
    from . import _coldpool

    HAS_COMPILED_KERNEL = True
except ImportError:  # pragma: no cover - depends on the build
    _coldpool = None
    HAS_COMPILED_KERNEL = False

G = 9.80665  # standard gravity [m s-2]

_ATTRS = {
    "mixing_ratio": {
        "standard_name": "humidity_mixing_ratio",
        "long_name": "Water vapour mixing ratio",
        "units": "kg kg-1",
    },
    "potential_temperature": {
        "standard_name": "air_potential_temperature",
        "long_name": "Potential temperature",
        "units": "K",
    },
    "virtual_potential_temperature": {
        "long_name": "Virtual potential temperature",
        "units": "K",
    },
    "equivalent_potential_temperature": {
        "standard_name": "equivalent_potential_temperature",
        "long_name": "Equivalent potential temperature (Bolton 1980, eq. 43)",
        "units": "K",
    },
    "buoyancy": {
        "long_name": "Buoyancy relative to the reference state",
        "units": "m s-2",
    },
    "cold_pool_intensity": {
        "long_name": "Cold-pool intensity C = sqrt(2 integral of -B dz)",
        "units": "m s-1",
    },
    "cold_pool_depth": {
        "long_name": "Depth of the cold pool above the lowest valid level",
        "units": "m",
    },
    "cold_pool_top_found": {
        "long_name": "Whether the top of the cold pool lies within the profile",
        "comment": "False: the deficit reaches the top of the data, so the depth "
        "and intensity are lower bounds",
    },
    "rkw_ratio": {
        "long_name": "Ratio of cold-pool intensity to line-normal shear, C / du",
        "units": "1",
    },
}


# --------------------------------------------------------------------------
# engine selection
# --------------------------------------------------------------------------


def _use_compiled(engine):
    """Whether to run the compiled kernel for the requested ``engine``."""
    if engine not in ("auto", "compiled", "numpy"):
        raise ValueError(
            f"engine must be 'auto', 'compiled' or 'numpy', not {engine!r}"
        )
    if engine == "compiled" and not HAS_COMPILED_KERNEL:
        raise ImportError("the compiled cold-pool kernel is not available")
    return HAS_COMPILED_KERNEL and engine != "numpy"


def _kernel(engine):
    return _coldpool if _use_compiled(engine) else _coldpool_numpy


def _f64(a):
    return np.ascontiguousarray(a, dtype=np.float64)


def _threads(n_threads):
    return int(n_threads or 0)


# --------------------------------------------------------------------------
# columns
# --------------------------------------------------------------------------


def _height_of(obj, dim, height):
    """Height of every element of ``obj`` (DataArray broadcast like ``obj``)."""
    if height is not None:
        z = height if isinstance(height, xr.DataArray) else obj[height]
    elif dim in obj.coords:
        z = obj[dim]
    else:
        raise ValueError(f"no coordinate {dim!r} to use as height; pass height=")
    return z


def _columns(arrays, dim, z):
    """Stack DataArrays into (ncol, nz) NumPy columns along ``dim``.

    Returns the columns (in the order of ``arrays``), the height columns,
    the dimensions and coordinates of the result without ``dim``, and the
    shape to restore.
    """
    arrays = xr.broadcast(*arrays, z)
    z = arrays[-1]
    arrays = arrays[:-1]
    if dim not in arrays[0].dims:
        raise ValueError(f"dimension {dim!r} not found in {arrays[0].dims}")
    other = [d for d in arrays[0].dims if d != dim]
    order = other + [dim]
    shape = tuple(arrays[0].sizes[d] for d in other)
    nz = arrays[0].sizes[dim]
    cols = [_f64(a.transpose(*order).values.reshape(-1, nz)) for a in arrays]
    zc = _f64(z.transpose(*order).values.reshape(-1, nz))
    # levels must increase along each column
    if nz > 1:
        first = np.nanmedian(np.diff(zc, axis=1))
        if np.isfinite(first) and first < 0:
            cols = [_f64(c[:, ::-1]) for c in cols]
            zc = _f64(zc[:, ::-1])
    coords = {
        k: v
        for k, v in arrays[0].coords.items()
        if dim not in v.dims and set(v.dims) <= set(other)
    }
    return cols, zc, other, coords, shape


def _per_column(value, template_dims, coords, shape):
    """Scalar or DataArray ``value`` as a flat array, one per column."""
    if value is None:
        return np.full(int(np.prod(shape, dtype=np.int64)), np.nan)
    if isinstance(value, xr.DataArray):
        tmpl = xr.DataArray(np.zeros(shape), dims=template_dims)
        value = value.broadcast_like(tmpl).transpose(*template_dims)
        return _f64(value.values.reshape(-1))
    return np.full(int(np.prod(shape, dtype=np.int64)), float(value))


# --------------------------------------------------------------------------
# thermodynamics
# --------------------------------------------------------------------------


def _dewpoint(ds, temperature, dewpoint, relative_humidity):
    if dewpoint in ds:
        return ds[dewpoint]
    if relative_humidity in ds:
        from ..io.sounding import (
            dewpoint_from_vapor_pressure,
            saturation_vapor_pressure,
        )

        rh = ds[relative_humidity]
        if rh.attrs.get("units") == "%" or float(rh.max(skipna=True).fillna(0)) > 2:
            raise ValueError("relative_humidity must be a fraction (units '1')")
        return dewpoint_from_vapor_pressure(
            rh * saturation_vapor_pressure(ds[temperature])
        )
    return xr.full_like(ds[temperature], np.nan)


def _check_si(t, p):
    tmax = float(np.nanmax(t)) if np.isfinite(t).any() else np.nan
    pmax = float(np.nanmax(p)) if np.isfinite(p).any() else np.nan
    if np.isfinite(tmax) and tmax < 150:
        raise ValueError("temperature must be in K")
    if np.isfinite(pmax) and pmax < 2000:
        raise ValueError("pressure must be in Pa")


def potential_temperatures(
    ds,
    *,
    temperature="temperature",
    pressure="pressure",
    dewpoint="dewpoint",
    relative_humidity="relative_humidity",
    engine="auto",
    n_threads=None,
):
    """
    Mixing ratio and potential, virtual potential and equivalent potential
    temperature.

    Parameters
    ----------
    ds : xarray.Dataset
        Temperature (K) and pressure (Pa), with the dew point (K) or, failing
        that, the relative humidity (fraction), e.g. a station network from
        :func:`radarx.io.read_sticknet`, a sounding from
        :mod:`radarx.io.sounding` or gridded fields. Without humidity only the
        potential temperature is finite.
    temperature, pressure, dewpoint, relative_humidity : str, optional
        Variable names.
    engine : {"auto", "compiled", "numpy"}, optional
        Kernel implementation.
    n_threads : int, optional
        Threads for the compiled kernel. Default: all cores.

    Returns
    -------
    xarray.Dataset
        ``mixing_ratio``, ``potential_temperature``,
        ``virtual_potential_temperature`` and
        ``equivalent_potential_temperature`` on the coordinates of ``ds``.

    References
    ----------
    Bolton, D., 1980: The computation of equivalent potential temperature.
    *Mon. Wea. Rev.*, **108** (7), 1046-1053,
    https://doi.org/10.1175/1520-0493(1980)108<1046:TCOEPT>2.0.CO;2
    """
    t, p = xr.broadcast(ds[temperature], ds[pressure])
    td = _dewpoint(ds, temperature, dewpoint, relative_humidity)
    t, p, td = xr.broadcast(t, p, td)
    _check_si(t.values, p.values)
    k = _kernel(engine)
    res = np.asarray(
        k.thermo(
            _f64(t.values.reshape(-1)),
            _f64(p.values.reshape(-1)),
            _f64(td.values.reshape(-1)),
            n_threads=_threads(n_threads),
        )
    )
    names = (
        "mixing_ratio",
        "potential_temperature",
        "virtual_potential_temperature",
        "equivalent_potential_temperature",
    )
    out = xr.Dataset(
        {
            n: t.copy(data=res[i].reshape(t.shape)).rename(n).assign_attrs(_ATTRS[n])
            for i, n in enumerate(names)
        }
    )
    for n in names:
        out[n].attrs = dict(_ATTRS[n])
    return out


def buoyancy(theta_v, reference, *, condensate=None):
    """
    Buoyancy from the virtual potential temperature.

    :math:`B = g (\\theta_v - \\overline{\\theta_v}) / \\overline{\\theta_v}
    - g r_c`.

    Parameters
    ----------
    theta_v : xarray.DataArray
        Virtual potential temperature (K).
    reference : xarray.DataArray or float
        Reference (environmental) virtual potential temperature, broadcast
        against ``theta_v``.
    condensate : xarray.DataArray or float, optional
        Condensate mixing ratio (kg kg-1) for the hydrometeor loading. Without
        it the buoyancy of precipitating air is overestimated (the cold-pool
        intensity underestimated).

    Returns
    -------
    xarray.DataArray
        ``buoyancy`` (m s-2) on the coordinates of ``theta_v``.

    References
    ----------
    Markowski, P., and Y. Richardson, 2010: *Mesoscale Meteorology in
    Midlatitudes*. Wiley-Blackwell, 407 pp.,
    https://doi.org/10.1002/9780470682104
    """
    b = G * (theta_v - reference) / reference
    if condensate is not None:
        b = b - G * condensate
    b = b.rename("buoyancy")
    b.attrs = dict(_ATTRS["buoyancy"])
    return b


def cold_pool_perturbation(
    ds,
    reference,
    *,
    dim="time",
    variables=None,
    engine="auto",
    n_threads=None,
):
    """
    Perturbations from a reference state and the buoyancy.

    Parameters
    ----------
    ds : xarray.Dataset
        Observations with ``temperature`` and ``pressure`` (and humidity),
        e.g. stations on ``(station, time)`` or a post-storm sounding on
        ``height``. Missing potential temperatures are computed with
        :func:`potential_temperatures`.
    reference : slice, xarray.Dataset
        The reference state: a ``slice`` of ``dim`` (e.g. a pre-storm time
        window) averaged over that window for every other coordinate (every
        station), or a Dataset (e.g. a pre-storm sounding) with the same
        variables. A reference sounding on other heights is interpolated to
        the heights of ``ds`` (:func:`radarx.io.sounding.interpolate_profile`).
    dim : str, optional
        Dimension that ``reference`` slices. Default ``"time"``.
    variables : list of str, optional
        Variables to perturb. Default: the potential temperatures,
        ``temperature``, ``pressure``, ``dewpoint`` and ``mixing_ratio``
        where present.
    engine, n_threads : optional
        For :func:`potential_temperatures`.

    Returns
    -------
    xarray.Dataset
        ``<name>_perturbation`` for every variable (the observation minus the
        reference), the reference ``virtual_potential_temperature_reference``
        and ``buoyancy`` from the virtual potential temperature.
    """
    ds = _with_thermo(ds, engine, n_threads)
    if isinstance(reference, slice):
        ref = ds.sel({dim: reference}).mean(dim, keep_attrs=True)
    elif isinstance(reference, xr.Dataset):
        ref = _with_thermo(reference, engine, n_threads)
        if "height" in ds.dims and "height" in ref.dims:
            if ref.sizes["height"] != ds.sizes["height"] or not np.allclose(
                ref["height"].values, ds["height"].values
            ):
                from ..io.sounding import interpolate_profile

                ref = interpolate_profile(
                    ref,
                    ds["height"],
                    [v for v in ref.data_vars if "height" in ref[v].dims],
                )
    else:
        raise TypeError("reference must be a slice or an xarray.Dataset")
    if variables is None:
        variables = [
            v
            for v in (
                "potential_temperature",
                "virtual_potential_temperature",
                "equivalent_potential_temperature",
                "temperature",
                "dewpoint",
                "mixing_ratio",
                "pressure",
            )
            if v in ds and v in ref
        ]
    out = xr.Dataset()
    for v in variables:
        d = (ds[v] - ref[v]).rename(f"{v}_perturbation")
        d.attrs = {
            "long_name": f"{ds[v].attrs.get('long_name', v)} minus reference",
            "units": ds[v].attrs.get("units", ""),
        }
        out[d.name] = d
    thv0 = ref["virtual_potential_temperature"]
    out["virtual_potential_temperature_reference"] = thv0.assign_attrs(
        long_name="Reference virtual potential temperature", units="K"
    )
    out["buoyancy"] = buoyancy(ds["virtual_potential_temperature"], thv0)
    return out


def _with_thermo(ds, engine, n_threads):
    if "virtual_potential_temperature" in ds:
        return ds
    pt = potential_temperatures(ds, engine=engine, n_threads=n_threads)
    return ds.assign({name: pt[name] for name in pt.data_vars})


# --------------------------------------------------------------------------
# cold-pool intensity
# --------------------------------------------------------------------------


def cold_pool_intensity(
    buoyancy,
    *,
    dim="height",
    height=None,
    threshold=0.0,
    depth=None,
    bottom=None,
    engine="auto",
    n_threads=None,
):
    """
    Cold-pool intensity :math:`C = \\sqrt{2 \\int_0^H (-B)\\, dz}` and depth.

    Parameters
    ----------
    buoyancy : xarray.DataArray
        Buoyancy (m s-2) with a vertical dimension ``dim``, e.g. from
        :func:`cold_pool_perturbation` of a post-storm sounding, or gridded
        (``z``, ``y``, ``x``) with any other dimensions (all columns are
        computed in one kernel call).
    dim : str, optional
        Vertical dimension. Default ``"height"``.
    height : str or xarray.DataArray, optional
        Heights (m) of the levels if not the ``dim`` coordinate (e.g. a 3-D
        height coordinate).
    threshold : float, optional
        Buoyancy (m s-2) that marks the top of the cold pool: the depth is the
        lowest height above the lowest valid level where ``B >= threshold``
        (linearly interpolated). Default 0. A slightly negative value (e.g.
        -0.005) ignores weak deficits above the cold pool.
    depth : float, optional
        Integrate over this fixed depth (m) above the lowest valid level
        instead of searching the top; NaN if the profile is shorter.
    bottom : float or xarray.DataArray, optional
        Ignore levels below this height (m), e.g. the ground. Default: start
        at the lowest valid level.
    engine : {"auto", "compiled", "numpy"}, optional
        Kernel implementation.
    n_threads : int, optional
        Threads for the compiled kernel. Default: all cores.

    Returns
    -------
    xarray.Dataset
        ``cold_pool_intensity`` (m s-1), ``cold_pool_depth`` (m) and
        ``cold_pool_top_found`` (bool) per column. Columns whose lowest level
        is not negatively buoyant have zero intensity and depth.

    References
    ----------
    Rotunno, R., J. B. Klemp, and M. L. Weisman, 1988: A theory for strong,
    long-lived squall lines. *J. Atmos. Sci.*, **45** (3), 463-485,
    https://doi.org/10.1175/1520-0469(1988)045<0463:ATFSLL>2.0.CO;2

    Bryan, G. H., J. C. Knievel, and M. D. Parker, 2006: A multimodel
    assessment of RKW theory's relevance to squall-line characteristics.
    *Mon. Wea. Rev.*, **134** (10), 2772-2792,
    https://doi.org/10.1175/MWR3226.1
    """
    z = _height_of(buoyancy, dim, height)
    (b,), zc, other, coords, shape = _columns([buoyancy], dim, z)
    bot = _per_column(bottom, other, coords, shape)
    top = _per_column(depth, other, coords, shape)
    k = _kernel(engine)
    res = np.asarray(
        k.cold_pool(zc, b, bot, float(threshold), top, n_threads=_threads(n_threads))
    )
    out = xr.Dataset(coords=coords)
    names = ("cold_pool_intensity", "cold_pool_depth")
    for i, n in enumerate(names):
        out[n] = xr.DataArray(res[i].reshape(shape), dims=other, attrs=_ATTRS[n])
    found = res[2].reshape(shape)
    out["cold_pool_top_found"] = xr.DataArray(
        np.where(np.isfinite(found), found == 0, False),
        dims=other,
        attrs=_ATTRS["cold_pool_top_found"],
    )
    out.attrs["threshold"] = float(threshold)
    if depth is not None:
        out.attrs["depth"] = depth if np.isscalar(depth) else "per column"
    return out


def cold_pool_intensity_from_pressure(pressure_perturbation, density=1.2):
    """
    Cold-pool intensity from the hydrostatic surface pressure excess.

    :math:`C = \\sqrt{2 \\Delta p / \\rho}`, which equals
    :math:`\\sqrt{2 \\int_0^H (-B) dz}` when the pressure excess under the
    cold pool is hydrostatic. Non-hydrostatic (dynamic) pressure, e.g. the
    jump at the gust front, should be excluded from ``pressure_perturbation``.

    Parameters
    ----------
    pressure_perturbation : xarray.DataArray
        Pressure excess over the reference (Pa); values <= 0 give zero.
    density : float or xarray.DataArray, optional
        Air density (kg m-3). Default 1.2.

    Returns
    -------
    xarray.DataArray
        ``cold_pool_intensity`` (m s-1).

    References
    ----------
    Benjamin, T. B., 1968: Gravity currents and related phenomena. *J. Fluid
    Mech.*, **31** (2), 209-248, https://doi.org/10.1017/S0022112068000133

    Wakimoto, R. M., 1982: The life cycle of thunderstorm gust fronts as
    viewed with Doppler radar and rawinsonde data. *Mon. Wea. Rev.*, **110**
    (8), 1060-1082,
    https://doi.org/10.1175/1520-0493(1982)110<1060:TLCOTG>2.0.CO;2
    """
    c = np.sqrt(2.0 * pressure_perturbation.clip(min=0.0) / density)
    c = c.rename("cold_pool_intensity")
    c.attrs = dict(_ATTRS["cold_pool_intensity"])
    c.attrs["comment"] = "from the surface pressure excess, C = sqrt(2 dp / rho)"
    return c


def cold_pool_intensity_from_surface(buoyancy, depth, *, shape="linear"):
    """
    Cold-pool intensity from the surface buoyancy and an assumed depth.

    Parameters
    ----------
    buoyancy : xarray.DataArray
        Surface buoyancy (m s-2), e.g. from :func:`cold_pool_perturbation`
        of a station network; values >= 0 give zero.
    depth : float or xarray.DataArray
        Cold-pool depth (m), e.g. from soundings
        (:func:`cold_pool_intensity`).
    shape : {"linear", "uniform"}, optional
        Buoyancy decreasing linearly from the surface value to zero at
        ``depth`` (:math:`C^2 = -B_s H`, default) or constant up to ``depth``
        (:math:`C^2 = -2 B_s H`).

    Returns
    -------
    xarray.DataArray
        ``cold_pool_intensity`` (m s-1).

    References
    ----------
    Rotunno, R., J. B. Klemp, and M. L. Weisman, 1988: A theory for strong,
    long-lived squall lines. *J. Atmos. Sci.*, **45** (3), 463-485,
    https://doi.org/10.1175/1520-0469(1988)045<0463:ATFSLL>2.0.CO;2
    """
    factors = {"linear": 1.0, "uniform": 2.0}
    if shape not in factors:
        raise ValueError(f"shape must be 'linear' or 'uniform', not {shape!r}")
    c = np.sqrt(factors[shape] * (-buoyancy).clip(min=0.0) * depth)
    c = c.rename("cold_pool_intensity")
    c.attrs = dict(_ATTRS["cold_pool_intensity"])
    c.attrs["comment"] = f"from the surface buoyancy and depth, {shape} profile"
    return c


def rkw_ratio(intensity, shear):
    """
    RKW ratio :math:`C / \\Delta u`.

    Parameters
    ----------
    intensity : xarray.DataArray or float
        Cold-pool intensity :math:`C` (m s-1).
    shear : xarray.DataArray or float
        Line-normal bulk wind difference over the low-level layer (m s-1),
        positive when the low-level shear points toward the inflow (the
        direction the cold pool spreads), e.g. ``shear_normal`` of
        :func:`radarx.retrieve.bulk_shear`.

    Returns
    -------
    xarray.DataArray
        ``rkw_ratio``; about 1 is the optimal state of Rotunno et al. (1988),
        > 1 a cold pool that dominates the shear (upshear-tilted system).

    References
    ----------
    Rotunno, R., J. B. Klemp, and M. L. Weisman, 1988: A theory for strong,
    long-lived squall lines. *J. Atmos. Sci.*, **45** (3), 463-485,
    https://doi.org/10.1175/1520-0469(1988)045<0463:ATFSLL>2.0.CO;2

    Weisman, M. L., and R. Rotunno, 2004: "A theory for strong long-lived
    squall lines" revisited. *J. Atmos. Sci.*, **61** (4), 361-382,
    https://doi.org/10.1175/1520-0469(2004)061<0361:ATFSLS>2.0.CO;2
    """
    r = xr.DataArray(intensity) / shear
    r = r.rename("rkw_ratio")
    r.attrs = dict(_ATTRS["rkw_ratio"])
    return r


# --------------------------------------------------------------------------
# baroclinic generation
# --------------------------------------------------------------------------


def baroclinic_generation(
    buoyancy,
    *,
    x="x",
    y="y",
    u=None,
    v=None,
    storm_motion=(0.0, 0.0),
    engine="auto",
    n_threads=None,
):
    """
    Baroclinic generation of horizontal vorticity, :math:`\\partial B /
    \\partial y` and :math:`-\\partial B / \\partial x`.

    Parameters
    ----------
    buoyancy : xarray.DataArray
        Buoyancy (m s-2) on a grid with horizontal dimensions ``y`` and ``x``
        (coordinates in m), and any others (height, time), e.g.
        ``buoyancy(theta_v, reference)`` of a radarx grid, or
        :math:`g\\,\\Delta T / T` of the accumulated evaporative cooling of
        :func:`radarx.retrieve.integrate_evaporation`. A vertical cross-section
        without ``y`` gives only :math:`-\\partial B / \\partial x`.
    x, y : str, optional
        Horizontal dimensions. Default ``"x"`` and ``"y"``.
    u, v : xarray.DataArray, optional
        Wind components along ``x`` and ``y`` (m s-1), e.g. multi-Doppler
        winds, broadcastable against ``buoyancy``. With them the generation is
        split into streamwise and crosswise parts relative to the
        storm-relative wind.
    storm_motion : tuple of float or xarray.Dataset, optional
        Storm motion ``(cx, cy)`` (m s-1) subtracted from ``u`` and ``v``, or
        a Dataset with ``u`` and ``v`` (e.g.
        :func:`radarx.retrieve.bunkers_storm_motion`). Default (0, 0).
    engine : {"auto", "compiled", "numpy"}, optional
        Kernel implementation.
    n_threads : int, optional
        Threads for the compiled kernel. Default: all cores.

    Returns
    -------
    xarray.Dataset
        ``dB_dx`` and ``dB_dy`` (s-2), the generation rates
        ``vorticity_x_generation`` (:math:`\\partial B/\\partial y`),
        ``vorticity_y_generation`` (:math:`-\\partial B/\\partial x`) and
        ``horizontal_vorticity_generation`` (their magnitude), all in s-2,
        and, with winds, ``streamwise_vorticity_generation`` and
        ``crosswise_vorticity_generation`` (s-2).

    References
    ----------
    Rotunno, R., J. B. Klemp, and M. L. Weisman, 1988: A theory for strong,
    long-lived squall lines. *J. Atmos. Sci.*, **45** (3), 463-485,
    https://doi.org/10.1175/1520-0469(1988)045<0463:ATFSLL>2.0.CO;2

    Davies-Jones, R., 1984: Streamwise vorticity: The origin of updraft
    rotation in supercell storms. *J. Atmos. Sci.*, **41** (20), 2991-3006,
    https://doi.org/10.1175/1520-0469(1984)041<2991:SVTOOU>2.0.CO;2
    """
    if x not in buoyancy.dims:
        raise ValueError(f"dimension {x!r} not found in {buoyancy.dims}")
    has_y = y in buoyancy.dims
    b = buoyancy if has_y else buoyancy.expand_dims({y: [0.0]})
    other = [d for d in b.dims if d not in (y, x)]
    arr = b.transpose(*other, y, x)
    ny, nx = arr.sizes[y], arr.sizes[x]
    flat = _f64(arr.values.reshape(-1, ny, nx))
    xc = _f64(arr[x].values) if x in arr.coords else np.arange(nx, dtype=float)
    yc = _f64(arr[y].values) if y in arr.coords else np.arange(ny, dtype=float)
    k = _kernel(engine)
    res = np.asarray(k.gradient(flat, xc, yc, n_threads=_threads(n_threads)))
    dims = tuple(other) + (y, x)
    shape = arr.shape
    dbdx = arr.copy(data=res[0].reshape(shape))
    dbdy = arr.copy(data=res[1].reshape(shape))
    if not has_y:
        dbdx = dbdx.isel({y: 0}, drop=True)
        dbdy = None
        dims = tuple(d for d in dims if d != y)
    order = [d for d in buoyancy.dims]
    out = xr.Dataset(coords={k_: c for k_, c in buoyancy.coords.items()})
    out["dB_dx"] = dbdx.transpose(*order).assign_attrs(
        long_name="Buoyancy gradient along x", units="s-2"
    )
    gen_y = (-out["dB_dx"]).assign_attrs(
        long_name="Baroclinic generation of horizontal vorticity along y " "(-dB/dx)",
        units="s-2",
    )
    out["vorticity_y_generation"] = gen_y
    if dbdy is None:
        out.attrs["comment"] = "vertical cross-section: only -dB/dx"
        return out
    out["dB_dy"] = dbdy.transpose(*order).assign_attrs(
        long_name="Buoyancy gradient along y", units="s-2"
    )
    gen_x = (
        out["dB_dy"]
        .copy()
        .assign_attrs(
            long_name="Baroclinic generation of horizontal vorticity along x (dB/dy)",
            units="s-2",
        )
    )
    out["vorticity_x_generation"] = gen_x
    out["horizontal_vorticity_generation"] = np.hypot(gen_x, gen_y).assign_attrs(
        long_name="Magnitude of the baroclinic generation of horizontal vorticity",
        units="s-2",
    )
    if u is not None and v is not None:
        if isinstance(storm_motion, xr.Dataset):
            cx, cy = storm_motion["u"], storm_motion["v"]
        else:
            cx, cy = storm_motion
        ur, vr = u - cx, v - cy
        speed = np.hypot(ur, vr)
        sx, sy = ur / speed, vr / speed
        out["streamwise_vorticity_generation"] = (gen_x * sx + gen_y * sy).assign_attrs(
            long_name="Baroclinic generation of streamwise horizontal vorticity",
            units="s-2",
            comment="component along the storm-relative wind",
        )
        out["crosswise_vorticity_generation"] = (-gen_x * sy + gen_y * sx).assign_attrs(
            long_name="Baroclinic generation of crosswise horizontal vorticity",
            units="s-2",
            comment="component 90 degrees to the left of the storm-relative wind",
        )
    return out


# --------------------------------------------------------------------------
# accessors
# --------------------------------------------------------------------------


@accessor_method("dataset", name="potential_temperatures")
def _potential_temperatures_accessor(self, **kwargs):
    """
    Mixing ratio and potential, virtual potential and equivalent potential
    temperature of the dataset.

    See :func:`radarx.retrieve.potential_temperatures` for the parameters.

    Returns
    -------
    xarray.Dataset
        The four variables on the coordinates of the dataset.
    """
    return potential_temperatures(self.xarray_obj, **kwargs)


@accessor_method("dataarray", name="cold_pool_intensity")
def _cold_pool_intensity_accessor(self, **kwargs):
    """
    Cold-pool intensity and depth of a buoyancy field.

    See :func:`radarx.retrieve.cold_pool_intensity` for the parameters.

    Returns
    -------
    xarray.Dataset
        ``cold_pool_intensity``, ``cold_pool_depth`` and
        ``cold_pool_top_found`` per column.
    """
    return cold_pool_intensity(self.xarray_obj, **kwargs)


@accessor_method("dataarray", name="baroclinic_generation")
def _baroclinic_generation_accessor(self, **kwargs):
    """
    Baroclinic generation of horizontal vorticity from a gridded buoyancy.

    See :func:`radarx.retrieve.baroclinic_generation` for the parameters.

    Returns
    -------
    xarray.Dataset
        Buoyancy gradients and vorticity generation rates.
    """
    return baroclinic_generation(self.xarray_obj, **kwargs)
