codecov:
  # General settings
  require_ci_to_pass: yes  # Only upload coverage if CI passes

coverage:
  # Coverage metrics settings
  precision: 2  # Number of decimal places to display
  round: down  # Round down the coverage percentage
  range: "80...100"  # Expected coverage range for success

  status:
    # Default coverage status
    project:
      default:
        target: 80%  # Target minimum coverage for the entire project
        threshold: 1%  # Allowable drop before failing
        paths:
          - "radarx/"  # Specify the path for code to be covered

    # Coverage status for specific changes in pull requests
    patch:
      default:
        target: 80%
        threshold: 1%

parsers:
  # Parsers to use for processing code coverage reports
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: yes
      macro: no

comment:
  # Settings for the comment posted by Codecov on pull requests
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: yes  # Only post a comment if there are coverage changes

repository:
  # Files or directories to exclude from coverage
  exclude:
    - "setup.py"
    - "tests/*"
